### PR TITLE
Feature/viewer controller refactor

### PR DESCRIPTION
**Pull request by toloudis**
Problem
=======
Update usage of SimulariumController in simularium-viewer 2.8.0

Solution
========
Update viewer version and modify calls to `changeFile`

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

Change summary:
---------------
Some reformatting happened due to format-on-save in my editor.  If you view the side by side diff, you'll see the only changes are to the simularium-viewer version and the calls to `changeFile`

Steps to Verify:
----------------
run website and verify that trajectories load, drag and drop works, and state isn't corrupted when the trajectory is changed.

### CODE REVIEW

**Comment by toloudis** [comment]
> I'm not sure why, but when I pulled this branch, then ran `npm i` then `npm start`, drag and drop didn't work. I tried both v1 and v2 files and in both cases I just got an error message on the top right saying "Simularium files need 'spatialData' array".

Anything good in the console?   Are you connecting to dev server or staging server?

**Comment by schoinh** [comment]
> Anything good in the console? Are you connecting to dev server or staging server?

Oh why do I always forget to look in the console... In this case actin012_3.h5.simularium is the name of the file I drag and dropped.
image

I'm able to connect to staging server and load simulations from there. (not working with dev server but I expected that)

**Comment by toloudis** [comment]
> I'm not sure why, but when I pulled this branch, then ran `npm i` then `npm start`, drag and drop didn't work. I tried both v1 and v2 files and in both cases I just got an error message on the top right saying "Simularium files need 'spatialData' array".

Fixed!  sorry about that

**Review by schoinh — APPROVED** [review]

**Comment by EricJIsaac** [comment]
Attempting to load endocytosis using this branch is resulting in a pop-up "no file was detected" and no messages to the console. I'm connecting to the staging back-end. The same file loads correctly on master.

**Review by EricJIsaac — CHANGES_REQUESTED** [review]
Attempting to load endocytosis using this branch is resulting in a pop-up "no file was detected" and no messages to the console. I'm connecting to the staging back-end. The same file loads correctly on master.

**Comment by toloudis** [comment]
> Attempting to load endocytosis using this branch is resulting in a pop-up "no file was detected" and no messages to the console. I'm connecting to the staging back-end. The same file loads correctly on master.

I can't repro.  Can you describe your steps?

**Comment by EricJIsaac** [comment]
> > Attempting to load endocytosis using this branch is resulting in a pop-up "no file was detected" and no messages to the console. I'm connecting to the staging back-end. The same file loads correctly on master.
> 
> I can't repro. Can you describe your steps?

1. In `webpack/plugins.js` I changed the BACKEND_SERVER_IP for the DEV environment to point to the staging back-end `staging-node1-agentviz-backend.cellexplore.net` (since dev is still down afaik)
2. npm start
3. navigate to http://0.0.0.0:9001/viewer?trajFileName=endocytosis.simularium

**Comment by EricJIsaac** [comment]
no-file-detected

**Comment by schoinh** [comment]
> 1. In `webpack/plugins.js` I changed the BACKEND_SERVER_IP for the DEV environment to point to the staging back-end `staging-node1-agentviz-backend.cellexplore.net` (since dev is still down afaik)
> 2. npm start
> 3. navigate to http://0.0.0.0:9001/viewer?trajFileName=endocytosis.simularium

@EricJIsaac Did you `npm i`?

**Comment by toloudis** [comment]
> > 1. In `webpack/plugins.js` I changed the BACKEND_SERVER_IP for the DEV environment to point to the staging back-end `staging-node1-agentviz-backend.cellexplore.net` (since dev is still down afaik)
> > 2. npm start
> > 3. navigate to http://0.0.0.0:9001/viewer?trajFileName=endocytosis.simularium
> 
> @EricJIsaac Did you `npm i`?

Yeah I was thinking possible dependency conflicts too.  First thing I'd try is removing node_modules (but keep package_lock.json) and npm install.

**Comment by EricJIsaac** [comment]
I did run `npm -i`, but I'll try it again to verify that I didn't miss an error

**Comment by EricJIsaac** [comment]
Removing the node_modules folder and re-running `npm i` cleared it up; my mistake

**Review by EricJIsaac — APPROVED** [review]

**Comment by toloudis** [comment]
thank you both for pulling the code and testing it.  much appreciated!

**Pull request merged**
